### ISSUE TITLE
Can't get stack trace with Monolog & Symfony

### ISSUE THREAD

**Issue by benjamindulau** [rollbar/rollbar-php#342]
I definitely won't get the stack trace when using `Rollbar\Monolog\Handler\RollbarHandler` in my Symfony project.

Everything works like a charm with Rollbar v0.8 but I just can't have my stack trace with v1.4.
As recommended in the doc, I don't try to use the Monolog handler because it's outdated.

Here is my config:

```yaml
services:
    rollbar_logger:
        class: Rollbar\RollbarLogger
        arguments:
            -
                access_token: "%rollbar_token%"
                environment: "%kernel.environment%"
                root: "%kernel.project_dir%/"
                code_version: "%commit_id%"
                capture_error_stacktraces: true
                include_error_code_context: true
                include_exception_code_context: true
    rollbar.handler.monolog:
        class: Rollbar\Monolog\Handler\RollbarHandler
        arguments:
            - "@rollbar_logger"

monolog:
    handlers:
        main:
            type: fingers_crossed
            action_level: "%monolog_action_level%"
            handler: rollbar
            excluded_404s:
                 - ^/
        rollbar:
            type: service
            id: rollbar.handler.monolog
            level:  "%monolog_action_level%"
        console:
            type:   console
            level:  "%monolog_action_level%"
            bubble: true
```

Any idea?

**Comment by rivkahstandig3636** [comment]
We will take a look into this, sorry for the delay!

**Comment by ArturMoczulski** [comment]
What version of Symfony are you running?

**Comment by ArturMoczulski** [comment]
Closing the issue for now. Will reopen when OP gets back to us with his version of Symfony

**Comment by benjamindulau** [comment]
Hey, long time :)

Still no trace as of today with:
- Symfony 5.4
- rollbar/rollbar v2.1.0
- rollbar/rollbar-php-symfony-bundle v4.0.0

Config in `config/package/rollbar.yaml`:

```YAML
rollbar:
    enabled: true
    access_token: "%rollbar_token%"
    environment: "%active_site%-%kernel.environment%"
    code_version: "%commit_id%"
    capture_error_stacktraces: true
    include_error_code_context: true
    include_exception_code_context: true
```

Config in `config/package/prod/monolog.yaml`:
```YAML
monolog:
    handlers:
        main:
            type: fingers_crossed
            action_level: '%monolog_action_level%'
            handler: rollbar
            excluded_404s:
                - ^/
        rollbar:
            type: service
            id: Rollbar\Monolog\Handler\RollbarHandler
            level: '%monolog_action_level%'
        console:
            type: console
            level: '%monolog_action_level%'
            bubble: true
```

And we get that kind of error with no traceback at all:

![Capture d’écran 2021-12-15 à 11 20 05](https://user-images.githubusercontent.com/430689/146168928-2b4add61-e8d9-48ac-b2a7-3296d99229bc.png)

We just can't rollback to an older version of Rollbar from now on. Please address this issue, or point us to the right direction if this can be fixed by hacking the default handler.

Thanks guys ;-)
