### ISSUE TITLE
How to configure 'level' in integration with monolog?

### ISSUE THREAD

**Issue by NavyCoat** [rollbar/rollbar-php#412]
Currently i have:
monolog.yml
```
        rollbar:
            type: service
            level: notice
            id: Rollbar\Monolog\Handler\RollbarHandler
```
rollbar.yml
```
rollbar:
  enabled: true
  access_token: 'dfghjk'
  environment: 'development'
```

It's seems like parameter level isnt even passed to RollbarHandler constructor
```
    public function __construct(RollbarLogger $rollbarLogger, $level = Logger::ERROR, $bubble = true)
    {
        $this->rollbarLogger = $rollbarLogger;

        var_dump(
            $level, //'error'
        );
        die;

        parent::__construct($level, $bubble);
    }
```

How can I change `level` to notice?
